name: python advanced testing weekly
#
# Run the python directory testing on push and pull request
#
on: [push, pull_request]
  #branches:
  #    #- master
  schedule:
  #- cron: '2 23 * * SAT'  # every Saturday  at 2:23am
    - cron: '2 23 * * *'  # every day at 2:23am

jobs:
  pytest:
     runs-on: ubuntu-latest
     steps:
        # Checkout the code
        - name: checkout the code
          uses: actions/checkout@v2
          with:
            lfs: true
        - name: lfs pull
          uses: actions/checkout@v2
        - run: git lfs pull
        - name: conda env
          uses: conda-incubator/setup-miniconda@v2
          with:
            python-version: 3.7.9
            auto-activate-base: true
            channels: conda-forge
        - name: manage_exernals and LFS
          run: |
            git lfs install
            manage_externals/checkout_externals
            sudo mkdir -p /glade/p/cesmdata/inputdata
        - name: Run python tests
          shell: bash -l {0}
          env:
            CIME_MODEL: "cesm"
            CIME_DRIVER: "nuopc"
            CIME_TEST_PLATFORM: ubuntu-latest
          run: |
              ./py_env_create --dask
              cd python
              conda run -n ctsm_pylib_wdask make adv_test
              if [ $? != 0 ] exit -1
          continue-on-error: False
