name: python testing on push and PR
#
# Run the python directory testing on push and pull request
#
on: [push, pull_request]

jobs:
  pytest:
     runs-on: ubuntu-latest
     steps:
        # Checkout the code
        - name: checkout the code
          uses: actions/checkout@v2
          with:
            lfs: true
        - name: lfs pull
          uses: actions/checkout@v2
          run: git lfs pull
        - name: conda env
          uses: conda-incubator/setup-miniconda@v2
          with:
            python-version: 3.7.9
            auto-activate-base: true
            channels: conda-forge
        - name: manage_exernals and LFS
          run: |
            git lfs install
            manage_externals/checkout_externals
        - name: Run python tests
          shell: bash -l {0}
          run: |
              ./py_env_create --read-spec
              conda activate ctsm_pylib
              cd python
              make test
        - name: Run pylint
          shell: bash -l {0}
          run: |
              conda info
              conda env list
              conda activate ctsm_pylib
              cd python
              make lint
